### ISSUE TITLE
Contribution au projet Servofocus

### ISSUE THREAD

**Issue by TelecomAnin** [paulrouget/servofocus#25]
Bonsoir à vous , 

je suis Arthus anin élève ingénieur à IMT Atlantique (France). Nouveau dans la contribution aux logiciels libres je souhaiterais de votre part une aide pour de belles aventures.
A cet effet si possible est de me renseigner sur votre projet ou m'assigner une tache aussi minime soit elle afin de me rendre utile. Merci de me revenir .

Respectueusement !!!

**Comment by paulrouget** [comment]
Désolé, pour le moment le projet n'est pas à un stade ou l'on peut accepter des contributions.
