### ISSUE TITLE
Override OpenGLViewRenderer

### ISSUE THREAD

**Issue by paulrouget** [paulrouget/servofocus#3]
See: https://github.com/xamarin/Xamarin.Forms/blob/5272dd8df76a934fb75090449d1496ae40a310d0/Xamarin.Forms.Platform.Android/Renderers/OpenGLViewRenderer.cs#L36

I want to change 2 things in this function: call `setEGLContextClientVersion(3)` instead of `setEGLContextClientVersion(2)` and call `setEGLConfigChooser(8, 8, 8, 8, 24, 0)`.

**Comment by mfkl** [comment]
Pushed something. Let me know if that works.

**Comment by paulrouget** [comment]
Thanks. This works. It is properly overridden. Still have a Servo issue (see servo/webrender#1795) but it's unrelated.
