### ISSUE TITLE
Scroll events don't have momentum (inertia)

### ISSUE THREAD

**Issue by paulrouget** [paulrouget/servofocus#6]
When the user scrolls, and lift his finger, we don't get pan gesture anymore.

We need to get scroll events even when the user lifted his finger.

**Comment by mfkl** [comment]
I think the Xamain.Forms gesture is too limited and this will need to be implemented natively (see firefox-focus impl link in [commit](https://github.com/paulrouget/servofocus/commit/6e2b244f69bdc8928b5dda526aa0007c396fd030)).

Btw, I think it would be sane to move all calls to Servo (Interop) in the Core (Servofocus) platform agnostic project, if we can.

**Comment by paulrouget** [comment]
Agreed with both..

**Comment by paulrouget** [comment]
I'll do it in #6.
