### ISSUE TITLE
crash on InitWithEgl

### ISSUE THREAD

**Issue by mfkl** [paulrouget/servofocus#7]
So I improved the binding generation somewhat and wanted to push my changes, but when tested on Android, the call InitWithEgl crashes the mono VM. Just wondering if that's a known issue on your side or if I messed somewhere in the bindings? @paulrouget 

InitWithEgl is called from the Android ServoViewRenderer OnElementChanged.
Using latest libservobridge.so
```
E/mono-rt (13847):   at (wrapper managed-to-native) Servofocus.ServoSharp/__Internal.InitWithEgl (intptr,Servofocus.HostCallbacks/__Internal,Servofocus.ViewLayout/__Internal) <0x00007>
E/mono-rt (13847):   at Servofocus.ServoSharp.InitWithEgl (Servofocus.HostCallbacks,Servofocus.ViewLayout) [0x00011] 
E/mono-rt (13847):   at Servofocus.Android.ServoViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs1<Servofocus.ServoView>) [0x00197]

F/libc    (13847): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x7ff81f4298 in tid 13847 (wser.servofocus)

**Comment by paulrouget** [comment]
Known issue. This started when I introduced more complex structures.

This is my priority now.

**Comment by paulrouget** [comment]
Fixed.
