### ISSUE TITLE
For every call to Servo, make sure it returns ServoResult::Ok

### ISSUE THREAD

**Issue by paulrouget** [paulrouget/servofocus#9]
I'm sure there's a proper way in C# to check if `ServoResult::Ok` is returned or throw an exception otherwise.

**Comment by mfkl** [comment]
Which interop call are you referring to?

EDIT: All of them. Yes, OK.

**Comment by mfkl** [comment]
All interop calls currently do return that [enum](https://github.com/paulrouget/servofocus/blob/e2d935d2b677ac6bd348fb75eea760885e0da673/xamarin/ServoSharp/ServoSharp.cs#L14).

Question is, what should we do if it's not `Ok`? 
- Crash the app
- Display a popup with the enum value and keep on going 
- ?

**Comment by paulrouget** [comment]
Crash.

**Comment by mfkl** [comment]
Closed by [b5700ba](https://github.com/paulrouget/servofocus/commit/b5700bae63f0f98350db739167d075a467d87173)
